add_rules("mode.debug", "mode.release")

target("ftxui-screen")
    set_kind("static")
    set_languages("c++20")
    set_toolchains("llvm")
    add_includedirs("external/ftxui/include", "external/ftxui/src")
    add_headerfiles("external/ftxui/include/ftxui/screen/**.hpp")
    add_files("external/ftxui/src/ftxui/screen/*.cpp|*test*.cpp")

target("ftxui-dom")
    set_kind("static")
    set_languages("c++20")
    set_toolchains("llvm")
    add_includedirs("external/ftxui/include", "external/ftxui/src")
    add_headerfiles("external/ftxui/include/ftxui/dom/**.hpp")
    add_files("external/ftxui/src/ftxui/dom/*.cpp|*test*.cpp")

target("ftxui-component")
    set_kind("static")
    set_languages("c++20")
    set_toolchains("llvm")
    add_includedirs("external/ftxui/include", "external/ftxui/src")
    add_headerfiles("external/ftxui/include/ftxui/component/**.hpp")
    add_files("external/ftxui/src/ftxui/component/*.cpp|*test*.cpp|*fuzzer*.cpp")
    add_deps("ftxui-dom", "ftxui-screen")

target("FormulaRacing")
    set_kind("binary")
    set_languages("c++20")
    set_toolchains("llvm")
    add_includedirs("src", "external/ftxui/include")
    add_headerfiles("src/**.h")
    add_files("src/**.cpp")
    add_deps("ftxui-component", "ftxui-dom", "ftxui-screen")
    set_targetdir("build")