ALTER TABLE racing_teams
    ADD COLUMN IF NOT EXISTS wins INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS podiums INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS budget_cap DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS constructor_pos INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS chassis_model VARCHAR(255),
    ADD COLUMN IF NOT EXISTS graduates INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS is_feeder BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS energy_partner VARCHAR(255),
    ADD COLUMN IF NOT EXISTS battery_kwh DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS sustain_score INTEGER DEFAULT 0;
